version: "3.9"
services:
  web-app:
    image: nginx:1.21.6
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - "8000:80"
  nats:
    image: nats:2.8.2
    command: -js -c /app/nats.conf
    volumes:
      - "./nats.conf:/app/nats.conf"
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
      - "8080:8080"
